[project]
name = "worldweaver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.1",
    "flask-login>=0.6.3",
    "python-dotenv>=1.1.1",
    "toml>=0.10.2",
    "tomli>=2.2.1",
    "vertexai>=1.71.1",
]
